console.log("Hello World!");
console.log(typeof "Dave");
console.log(typeof 42);
console.log(typeof true);
const myVariable="Mathematics";
console.log(myVariable.length);
console.log("Every good boy does fine".length);
console.log(myVariable.charAt(7));
console.log(myVariable.indexOf('ati'));
console.log(myVariable.slice(5,8));
console.log(myVariable.toLowerCase());
console.log(myVariable.toUpperCase());
console.log(myVariable.includes("mat"));
console.log(myVariable.split("e"));
console.log(myVariable.split(""));
console.log("John,Joe,Dave".split(","));
console.log("Every good boy does fine".split(" "));
const myNumber =42;
const myFloat = 42.01;
console.log(myFloat);
console.log(myNumber === myFloat);
const myString ="42";
console.log((myString));
console.log(Number(myString));
console.log(Number(myString)+3);
console.log((myString)+3);
console.log(Number(myString)==myNumber);
console.log(Number("Dave"));
console.log(Number(true));